# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "debian/bullseye64"
  config.vm.network "forwarded_port", guest: 9090, host: 9090
  # config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
  end
  config.vm.provision "shell", inline: <<-SHELL
    apt update && apt -y dist-upgrade
    apt -y install docker.io
    docker run --name dvna -p 9090:9090 -d appsecco/dvna:sqlite
  SHELL
end
